### ISSUE TITLE
Reopening filtering causes errors

### ISSUE THREAD

**Issue by michalsgit** [IgniteUI/igniteui-angular#10048]
## Description  
Reopening filtering expression causes errors

 * igniteui-angular version: 12.1.1
 * browser: Chrome

## Steps to reproduce  

1. Got to filtering demo [here](https://stackblitz.com/github/IgniteUI/igniteui-live-editing-samples/tree/master/angular-demos/grid/grid-filter-conditions)

2. Open console

3. Click on filter in column "Discontinued"
4. Choose "True" OR "False "and click "Close" (same result will be with AND operand, too)
5. Click again on the filter

## Result  
Error occures:
preview-f4664a6cfd526d580909b.js:1 ERROR TypeError: Cannot read property 'iconName' of null
    at Object.eval [as updateDirectives] (IgxGridFilteringCellComponent.html:19)
    at Object.debugUpdateDirectives [as updateDirectives] (services.ts:390)
    at checkAndUpdateView (view.ts:372)
    at callViewAction (view.ts:628)
    at execEmbeddedViewsAction (view.ts:593)
    at checkAndUpdateView (view.ts:373)
    at callViewAction (view.ts:628)
    at execEmbeddedViewsAction (view.ts:593)
    at checkAndUpdateView (view.ts:373)
    at callViewAction (view.ts:628)

## Expected result  
No error should occure.

## Attachments  
Attach
![filter-error](https://user-images.githubusercontent.com/6318187/130473321-d0a2f3c8-bd39-4c70-a719-cef8dace6025.png)

**Comment by domJalb** [comment]
This same bug is in version 11

**Comment by michalsgit** [comment]
Still does not work in version 12.1.6

**Comment by kdinev** [comment]
@domJalb Reopening. The changes will be propagated to `11.1.x` and available in patch `11.1.26`. 

@astaev Please cherry-pick the fix in `11.1.x`

**Comment by kdinev** [comment]
@michalsgit Did you just update? It could be a cache issue. @onlyexeption Could you retest again with `12.1.x`?

**Comment by michalsgit** [comment]
@kdinev You are right, it was problem with the cache. Now it works. Thanks.

**Comment by kdinev** [comment]
@onlyexeption You can ignore my previous comment :)
