### ISSUE TITLE
[7.0.x] Error is thrown when a module from igniteui-angular is referenced in a sample application

### ISSUE THREAD

**Issue by tachojelev** [IgniteUI/igniteui-angular#3116]
### Description  
An error is thrown when a module from igniteui-angular is referenced in a sample application.

 * igniteui-angular version: 7.0.x
 * browser: any

**NOTES:**
- The issue is reproduced with **7.0.x** (current master), but is **not**  reproduced with **6.2.x**.

### Steps to reproduce  

0. **(Optional)** (For the below steps, you can use the attached sample application)
1. Build the code of the current **master** branch (7.0.x).
2. Go to dist/igniteui-angular and execute **npm link**
3. In any external sample application, enable preserveSymLinks in angular.json.
3. In the sample application, execute **npm link igniteui-angular**.
4. In the **app.module.ts** of the sample application, include any module from **igniteui-angular**.
(for example: **import { IgxGridModule } from 'igniteui-angular';**)
5. In the sample application, execute **ng serve**.

### Result  
The following error is thrown:
**"node_modules/igniteui-angular/lib/navigation-drawer/navigation-drawer.directives.d.ts(14,28): error TS1039: Initializers are not allowed in ambient contexts."**

![image](https://user-images.githubusercontent.com/12784974/48910600-0eb50d00-ee79-11e8-8e18-394fec60b576.png)

### Expected result  
No error is thrown and the sample application is compiled successfully.

[sampleApp.zip](https://github.com/IgniteUI/igniteui-angular/files/2608558/sampleApp.zip)

**Comment by rkaraivanov** [comment]
@tachojelev 

This is an issue with typescript 3.1+ and the way certain const/readonly members are outputted in the generated d.ts files. The attached application is build with Angular 6 and TS 2.6.x which throws the error when consuming d.ts files produced by TS 3.1+.

Possible solutions:

- Upgrade to Angular 7 and Typescript 3.1+
- Set `"skipLibCheck" : true"` inside your `tsconfig.json`.
